//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursach
{
    using System;
    using System.Collections.Generic;
    
    public partial class product_purchase
    {
        public Nullable<int> id_raw { get; set; }
        public Nullable<int> amount { get; set; }
        public Nullable<int> id_of_purchasing { get; set; }
        public int id { get; set; }
    
        public virtual purchase_invoice purchase_invoice { get; set; }
        public virtual raw raw { get; set; }
    }
}
