//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursach
{
    using System;
    using System.Collections.Generic;
    
    public partial class purchase_invoice
    {
        public purchase_invoice()
        {
            this.product_purchase = new HashSet<product_purchase>();
        }
    
        public int id_of_purchasing { get; set; }
        public Nullable<System.DateTime> date_of_purchasing { get; set; }
        public Nullable<int> id_of_supp { get; set; }
    
        public virtual ICollection<product_purchase> product_purchase { get; set; }
    }
}
