//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursach
{
    using System;
    using System.Collections.Generic;
    
    public partial class raw
    {
        public raw()
        {
            this.product_order = new HashSet<product_order>();
            this.product_purchase = new HashSet<product_purchase>();
            this.product_sales = new HashSet<product_sales>();
        }
    
        public int id_raw { get; set; }
        public string name_raw { get; set; }
    
        public virtual ICollection<product_order> product_order { get; set; }
        public virtual ICollection<product_purchase> product_purchase { get; set; }
        public virtual ICollection<product_sales> product_sales { get; set; }
    }
}
