//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursach
{
    using System;
    using System.Collections.Generic;
    
    public partial class sales_invoice
    {
        public Nullable<int> id_workshop { get; set; }
        public System.DateTime date_of_sale { get; set; }
        public int id_of_sailing { get; set; }
    }
}
